# Generated by Django 5.0.2 on 2024-02-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='fabric_cares',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='good',
        ),
        migrations.AddField(
            model_name='fabriccare',
            name='good',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goods.good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='delivery_and_return',
            field=models.ManyToManyField(to='goods.deliveryandreturn'),
        ),
        migrations.AddField(
            model_name='good',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='photos',
            field=models.ManyToManyField(to='goods.photo'),
        ),
        migrations.AddField(
            model_name='good',
            name='sizes',
            field=models.ManyToManyField(to='goods.size'),
        ),
    ]
