# Generated by Django 5.0.2 on 2024-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_good_fabric_cares_remove_photo_good_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='static/photos'),
        ),
    ]
