# Generated by Django 5.0.2 on 2024-02-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriccare',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_cares', to='goods.good'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='goods.good'),
        ),
        migrations.AlterField(
            model_name='good',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='goods.color'),
        ),
        migrations.AlterField(
            model_name='good',
            name='delivery_and_return',
            field=models.ManyToManyField(related_name='delivery_and_returns', to='goods.deliveryandreturn'),
        ),
        migrations.AlterField(
            model_name='good',
            name='photos',
            field=models.ManyToManyField(related_name='photos', to='goods.photo'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='goods.size'),
        ),
    ]
