# Generated by Django 5.0.2 on 2024-02-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_fabriccare_good_alter_feature_good_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gender',
            field=models.CharField(default='UNISEX', max_length=50),
        ),
    ]
