# Generated by Django 5.0.2 on 2024-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_remove_good_category_good_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_for_men',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_for_women',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
